_wandb:
    value:
        cli_version: 0.28.0
        e:
            m17l7sjm89sazgpdds46p7mk8q06r64b:
                codePath: /home/sandro/ML_final/model_experiment_XGBoost.ipynb
                codePathLocal: model_experiment_XGBoost.ipynb
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "249792131072"
                        used: "198344597504"
                email: slomi23@freeuni.edu.ge
                executable: /home/sandro/anaconda3/envs/cs224n/bin/python
                git:
                    commit: 45472b69feb860a5e4273fcd1213798cbfb3e6ea
                    remote: git@github.com:slomi23/ML_final.git
                host: sandro-Lenovo-V15-G2-ITL
                memory:
                    total: "20760645632"
                os: Linux-6.17.0-35-generic-x86_64-with-glibc2.39
                program: /home/sandro/ML_final/model_experiment_XGBoost.ipynb
                python: CPython 3.13.12
                root: /home/sandro/ML_final
                startedAt: "2026-07-11T07:33:06.391797Z"
                writerId: m17l7sjm89sazgpdds46p7mk8q06r64b
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 5
                - 6
                - 53
            "2":
                - 5
                - 6
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.12
            "5": 0.28.0
            "8":
                - 1
            "12": 0.28.0
            "13": linux-x86_64
early_stopping_rounds:
    value: 20
eval_metric:
    value: mae
learning_rate:
    value: 0.05
max_depth:
    value: 6
n_estimators:
    value: 500
objective:
    value: reg:squarederror
seed:
    value: 42
verbosity:
    value: 1
